const UPLOADTEAMIMAGE='UPLOADTEAMIMAGE'
const LATANDLONG='LATANDLONG'
const ISLOGGEDIN='ISLOGGEDIN'
const LOGINUSER='LOGINUSER'
const GETALLITEMS='GETALLITEMS'
const LOGINFIRSTALERT='LOGINFIRSTALERT'



export {
    UPLOADTEAMIMAGE,
    LATANDLONG,
    ISLOGGEDIN,
    LOGINUSER,
    GETALLITEMS,
    LOGINFIRSTALERT,
}
