const UPLOADTEAMIMAGE='UPLOADTEAMIMAGE'
const LATANDLONG='LATANDLONG'
const ISLOGGEDIN='ISLOGGEDIN'
const LOGINUSER='LOGINUSER'
const GETALLITEMS='GETALLITEMS'



export {
    UPLOADTEAMIMAGE,
    LATANDLONG,
    ISLOGGEDIN,
    LOGINUSER,
    GETALLITEMS,
}
